unique_ids:
  forms:
    Base_Template: XUN2HJEXECWWXKSG6NQJMMQJIFRZFP3U
  modules: {}
  server_modules: {}
  assets:
    standard-page.html: PQK6XNX76XF5TZ2WORBF5QGTEQTOPOTI
    theme.css: KMZ6XJHV2KWV7E4QLILPUGZDLVTU5SKI
